cmake_minimum_required(VERSION 3.26)
project(spbspu-labs-2023-aap-master/zhitnyj.dmitriy/P1)

set(CMAKE_CXX_STANDARD 14)

add_executable(spbspu-labs-2023-aap-master/zhitnyj.dmitriy/P1 main.cpp
        helpersFunc.h
        helperFunc.cpp)
